version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - PASSLIB_BACKEND=builtin
    depends_on:
      - db
    volumes:
      - .:/app  # So you can edit code live (optional for dev)

  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
